###############################################################
# SConscript for the Scheme PLT modules
#
# Should be ok for cross platform

import os
	 
Import("InstallEnv", "FluxusVersion", "CollectsLocation", "BinaryModulesLocation")

Scripts    = ["fluxus-boot.scm", 
			  "fluxus-canvas.ss", 
			  "fluxus-input.ss",
			  "fluxus-camera.ss",
			  "fluxus-obj-import.ss", 
			  "autodoc.ss" ]

Install        = CollectsLocation
InstallStartup = os.environ["HOME"]+"/.fluxus/"

InstallEnv.Install(Install, Scripts)
InstallEnv.Install(InstallStartup, ["startup.scm"])
InstallEnv.Alias('install', InstallStartup)
