###############################################################
# SConscript for the Scheme PLT modules
#
# Should be ok for cross platform

import os
Import("Prefix", "CollectsLocation", "BinaryModulesLocation")

Scripts    = ["fluxus-canvas.ss", 
			  "fluxus-obj-import.ss", 
			  "fluxus-camera.ss",
			  "autodoc.ss" ]

Install        = CollectsLocation
InstallStartup = os.environ["HOME"]+"/.fluxus/"

env = Environment()
env.Install(Install, Scripts)
env.Install(InstallStartup, ["startup.scm"])
env.Alias('install', Install)
env.Alias('install', InstallStartup)
